projects:
  amplifyexperiments:
    schemaPath: src/graphql/schema.json
    includes:
      - src/**/*gql.ts
    excludes:
      - ./amplify/**
      - ./src/graphql/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: 2nm4kqwei5bsra6sfgrhtxdioy
