projects:
  amplifyexperiments:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: vy4g4twi55difaruik6jthmohu
      endpoints:
        prod: >-
          https://jpawtc67nbcq7nv3id5tzy6t3y.appsync-api.eu-west-1.amazonaws.com/graphql
